Add emscripten configure script

diff --git a/qemu/configure-emscripten b/qemu/configure-emscripten
--- a/qemu/configure-emscripten
+++ b/qemu/configure-emscripten
@@ -53,7 +53,7 @@ print_error() {
 
 error_exit() {
     print_error "$@"
-    exit 1
+    #exit 1
 }
 
 do_compiler() {
@@ -419,8 +419,9 @@ else
   # This is a fatal error, but don't report it yet, because we
   # might be going to just print the --help text, or it might
   # be the result of a missing compiler.
-  targetos='bogus'
-  bogus_os='yes'
+  #targetos='bogus'
+  targetos="Linux"
+  #bogus_os='yes'
 fi
 
 # Some host OSes need non-standard checks for which CPU to use.
@@ -939,10 +940,12 @@ write_c_skeleton;
 if compile_object ; then
   : C compiler works ok
 else
-    error_exit "\"$cc\" either does not exist or does not work"
+  echo "Ignore"
+    #error_exit "\"$cc\" either does not exist or does not work"
 fi
 if ! compile_prog ; then
-    error_exit "\"$cc\" cannot build an executable (is your linker broken?)"
+  echo "Ignore"
+    #error_exit "\"$cc\" cannot build an executable (is your linker broken?)"
 fi
 
 # Now we have handled --enable-tcg-interpreter and know we're not just
@@ -991,9 +994,9 @@ cat > $TMPC << EOF
 #endif
 int main (void) { return 0; }
 EOF
-if ! compile_prog "" "" ; then
-    error_exit "You need at least GCC v4.8 or Clang v3.4 (or XCode Clang v5.1)"
-fi
+#if ! compile_prog "" "" ; then
+#    error_exit "You need at least GCC v4.8 or Clang v3.4 (or XCode Clang v5.1)"
+#fi
 
 gcc_flags="-Wold-style-declaration -Wold-style-definition -Wtype-limits"
 gcc_flags="-Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers $gcc_flags"
@@ -1072,10 +1075,10 @@ static __thread int tls_var;
 int main(void) { return tls_var; }
 EOF
 
-if ! compile_prog "-Werror" "" ; then
-    error_exit "Your compiler does not support the __thread specifier for " \
-	"Thread-Local Storage (TLS). Please upgrade to a version that does."
-fi
+#if ! compile_prog "-Werror" "" ; then
+#    error_exit "Your compiler does not support the __thread specifier for " \
+#	"Thread-Local Storage (TLS). Please upgrade to a version that does."
+#fi
 
 cat > $TMPC << EOF
 
@@ -1276,10 +1279,10 @@ else
   done
 fi
 
-if test "$mingw32" != yes && test "$pthread" = no; then
-  error_exit "pthread check failed" \
-      "Make sure to have the pthread libs and headers installed."
-fi
+#if test "$mingw32" != yes && test "$pthread" = no; then
+#  error_exit "pthread check failed" \
+#      "Make sure to have the pthread libs and headers installed."
+#fi
 
 # check for pthread_setname_np with thread id
 pthread_setname_np_w_tid=no
@@ -1455,7 +1458,6 @@ fi
 clock_adjtime=no
 cat > $TMPC <<EOF
 #include <time.h>
-#include <sys/timex.h>
 
 int main(void)
 {
@@ -1515,7 +1517,7 @@ if compile_prog "" "" ; then
 elif compile_prog "" "-lm" ; then
   LIBS="-lm $LIBS"
 else
-  error_exit "libm check failed"
+  : #error_exit "libm check failed"
 fi
 
 ##########################################
@@ -2152,24 +2154,26 @@ EOF
     cat > $TMPC << EOF
 #include "stdint.h"
 int main() {
-    uint64_t v;
+    uint64_t commpage_sprr = (*(uint64_t*)0xFFFFFC10C);
 
-    __asm__ __volatile__("isb sy\n"
-                          "mrs %0, S3_6_c15_c1_5\n"
-                          : "=r"(v)::"memory");
-    // In Apple Hypervisor virtualized environment (EL1), this value is not accessbile
-    // but pthread_jit_write_protect_np essentially is a no-op.
-    return 0;
+    // In Apple Hypervisor, this value is not accessbile and
+    // pthread_jit_write_protect_np essentially is a no-op
+    if (!commpage_sprr) {
+        return 1;
+    } else {
+        return 0;
+    }
 }
 EOF
     if ! compile_prog ""; then
-      have_sprr_mrs='no'
+      have_sprr='no'
+      have_pthread_jit_protect='no'
     else
       $TMPE
       if [ $? -eq 0 ]; then
-        have_sprr_mrs='yes'
+        have_sprr='yes'
       else
-        have_sprr_mrs='no'
+        have_sprr='no'
       fi
     fi
   fi
@@ -2388,7 +2392,7 @@ else
 fi
 
 if test "$linux" = "yes" ; then
-  echo "CONFIG_LINUX=y" >> $config_host_mak
+  echo "CONFIG_LINUX=n" >> $config_host_mak
 fi
 
 if test "$darwin" = "yes" ; then
@@ -2553,8 +2557,8 @@ if test "$have_pthread_jit_protect" = "yes" ; then
   echo "HAVE_PTHREAD_JIT_PROTECT=y" >> $config_host_mak
 fi
 
-if test "$have_sprr_mrs" = "yes" ; then
-  echo "HAVE_SPRR_MRS=y" >> $config_host_mak
+if test "$have_sprr" = "yes" ; then
+  echo "HAVE_SPRR=y" >> $config_host_mak
 fi
 
 # Hold two types of flag:
